### ISSUE TITLE
XmppWebSocketConnection class

### ISSUE THREAD

**Issue by ForNeVeR** [vitalyster/SharpXMPP#11]
Currently the compilation of [`XmppSocketConnection` class](https://github.com/vitalyster/SharpXMPP/blob/8c0b745fc38b00289675ad531077cea03bede9e8/SharpXMPP.Shared/XmppWebSocketConnection.cs) is disabled. I had to disable it in scope of .NET Core porting, because it uses `WebSocket4Net`, but there's no `WebSocket4Net` dependency in the project and I had no time to address that properly.

What should we do now? There's an issue #6. @vitalyster, do you have plans to revive this class in its scope?

**Comment by vitalyster** [comment]
there is a WIP 8ecad501e46be83

**Comment by ForNeVeR** [comment]
Alright. Let this issue to stay until this branch will be merged.

**Comment by vitalyster** [comment]
Why #6 is not enough? :)

**Comment by ForNeVeR** [comment]
Because #6 describes the new feature, and #11 describes the unpleasantness we already have in the master branch right now. If somebody found that semi-disabled `XmppSocketConnection` class, we'll need to direct him to the proper issue!
