### ISSUE TITLE
Ways to close existing connections + WebSocket dispose issues

### ISSUE THREAD

**Issue by kimimaru4000** [vitalyster/SharpXMPP#164]
Hi, this issue concerns a few things:

1. Is there a way to disconnect an existing `XMPPWebSocketConnection` or `XmppTcpConnection` and reopen them later? I don't see methods exposing some of these.
2. `XMPPWebSocketConnection` does not override `Dispose` to dispose the WebSocket object. This may result in memory leaks.

**Comment by ForNeVeR** [comment]
> Is there a way to disconnect an existing `XMPPWebSocketConnection` or `XmppTcpConnection` and reopen them later? I don't see methods exposing some of these.

I don't think it is. What's the use case, though?

> `XMPPWebSocketConnection` does not override `Dispose` to dispose the WebSocket object. This may result in memory leaks.

I agree that there's a problem. Wanna send a PR with a fix?

**Comment by kimimaru4000** [comment]
> I don't think it is. What's the use case, though?

This would allow reusing the connection object by altering its state instead of having to dispose/recreate them. In my case, it would simplify manual reconnections since I would be able to disconnect then reconnect without having to subscribe to all events, etc again.

On the API side, it's more clear: since there's an API for connecting, I would expect one for disconnecting. Disposing implies that the object won't ever be used again, and it's not immediately clear to me how well it'd handle closing the connection.

> I agree that there's a problem. Wanna send a PR with a fix?

Here's a PR: https://github.com/vitalyster/SharpXMPP/pull/165

**Comment by ForNeVeR** [comment]
Both points are closed by #165.
