### ISSUE TITLE
Enable CI

### ISSUE THREAD

**Issue by ForNeVeR** [vitalyster/SharpXMPP#2]
The library should periodically build on Travis and Appveyor.

**Comment by vitalyster** [comment]
I've setup both, but appveyor can't find nunit, and travis failed on nuget restore :)

**Comment by ForNeVeR** [comment]
I'll take care of them.

**Comment by ForNeVeR** [comment]
Seems I don't need to. Everything works now.

**Comment by vitalyster** [comment]
please fix `dotnetcore` branch :)

**Comment by ForNeVeR** [comment]
Ok, planned to take a look.

**Comment by vitalyster** [comment]
there is a `project.json` for .NET Core target and it works with `dotnet`, but it breaks `msbuild` which imports `project.json` too besides `project.csproj`. Need somehow ignore `package.json` or update it for `net451` and `netcoreapp1.0` both

**Comment by ForNeVeR** [comment]
Yep, I thought that ideally we'll need to produce both CoreCLR and FullCLR builds from the same `project.json`. Will investigate.

**Comment by ForNeVeR** [comment]
I'll return to the issue after conducting experiments in scope of https://github.com/ForNeVeR/Jabber-Net/issues/61.
