### ISSUE TITLE
Port to .NET Core

### ISSUE THREAD

**Issue by ForNeVeR** [vitalyster/SharpXMPP#4]

**Comment by vitalyster** [comment]
I have successfully compile most of the code with .NET Core, except DNS resolver (ARSoft.Dns .NET Core package is not avalable in NuGet)

**Comment by vitalyster** [comment]
I've restored my quick and dirty DNS resolver and fix all other compatibility issues with .NET Core in 739ae340cbf578ef8e9c0282ad92efa5ec2bcaac

**Comment by ForNeVeR** [comment]
Well that's nice, but we need build instructions / scripts for both platforms.
