### ISSUE TITLE
MUC Support

### ISSUE THREAD

**Issue by AtifShahzed** [vitalyster/SharpXMPP#70]
I am using your library and pretty happy, I just looking for the MUC chat can you please guide me is this library supports MUC Conversation.

Thanks

**Comment by vitalyster** [comment]
`XmppClient` have `BookmarkManager` property and it has `Join` method, this will join MUC

**Comment by AtifShahzed** [comment]
I see,
I didn't find any snippet to join but there is method of join but it requires **BookmarkedConference** .
Can you please guide what room parameters do I need to add inside BookmarkedConference array object.
Following is my code.

 BookmarkedConference bookmarkedConference = new BookmarkedConference();
            bookmarkedConference.Add("room1@conference.blah.com");
            this._xmppconnetction.BookmarkManager.Join
      (bookmarkedConference);

Thanks

**Comment by vitalyster** [comment]
Set `JID` property of `BookmarkedConference`, like `bookmarkedConference.JID = new JID("room1@conference.blah.com");`

**Comment by AtifShahzed** [comment]
bookmarkedConference.JID Is Read-only.

**Comment by vitalyster** [comment]
https://github.com/vitalyster/SharpXMPP/blob/master/SharpXMPP.Shared/XMPP/Client/MUC/Bookmarks/Elements/BookmarkedCoference.cs#L28 - I see public setter there

**Comment by AtifShahzed** [comment]
I am receiving a send_direct_invitation request and parse into stanza and then try to join it but geeting following error.

![image](https://user-images.githubusercontent.com/54445953/92149289-41a27800-ee37-11ea-80de-ab7c9dbb56a5.png)

**Comment by AtifShahzed** [comment]
Hi,

Ya it requires stanza what I am doing now on receive message I am parsing the message into BookmarkedConference  but getting an error.

![image](https://user-images.githubusercontent.com/54445953/92149601-a78eff80-ee37-11ea-8af4-92b85221fc18.png)

Here is the message which I am receiving as a join request.
<message to="321789@blah.com" from="room2@conference.blah.com" xmlns="jabber:client">
  <x reason="Check this out!" password="1234" jid="room2@conference.blah.com" xmlns="jabber:x:conference" />
</message>

Should I pass a new stanza with only JID on join.

Thanks

**Comment by vitalyster** [comment]
What is "join request"? Do you have it in XML form? Generally you can't parse message into conference, these are totally different XML elements.

**Comment by vitalyster** [comment]
Also you should not overwrite BookmakrMnager property, it is create automatically and `Rooms` automatically populated with your bookmarked conferences.

**Comment by AtifShahzed** [comment]
Hi,

Here is the invitation request which is in XML.
<?xml version="1.0"?>

<message xmlns="jabber:client" from="room2@conference.bla.com" to="33789@bla.com">

<x xmlns="jabber:x:conference" jid="room2@conference.bla.com" password="1234" reason="Check this out!"/>

</message>

**Comment by AtifShahzed** [comment]
Hi,

I am trying to join using following code but still getting object reference error.

     BookmarkedConference room = new BookmarkedConference() { ID= "room1@conference.blah.com" };
        
            this._xmppconnetction.BookmarkManager = new  BookmarksManager(this._xmppconnetction);
            this._xmppconnetction.BookmarkManager.Join
      (room);

**Comment by vitalyster** [comment]
So, 
1) invitation request is a different XML element described in [XEP-0249](https://xmpp.org/extensions/xep-0249.html)
2) it is the *child* element of received message, so to extract room jid you need to find child element by name (`x`) and namespace (`jabber:x:conference`). You can use `XElement` methods on `XMPPMessage` (because `XMPPMessage` is `System.Xml.Linq.XElement`) to find that child element and get `jid` attribute from it. This should be easy if you familiar with LINQ to XML.
3) You *should not* overwrite BookmarkManager again, it is *already created*.

**Comment by AtifShahzed** [comment]
Hi,

Thanks a lot yap I am able to extract the JID from the xml but when I try to write the join request as per your suggestion I am not able to set the JID because it is get only property as you can see on screenshot.

![image](https://user-images.githubusercontent.com/54445953/92153948-749c3a00-ee3e-11ea-9587-606cd593b514.png)

**Comment by AtifShahzed** [comment]
Hi,

Well i downloaded the source code and create new test app by adding the source project as a reference to debug the issue.
Finally I have identified the issue.

Here is the MUC room joining code.
      this._xmppconnetction.BookmarkManager.Join(new BookmarkedConference()
            { JID = new JID("room2@conference.abc.com")});

When I debug it hits the Join method and grab the JID but NICK is null and that's why I was not able to join the room. Nick is also read only property.

Right now I am using the source code complied libraries but if you guide me is there any way to resolve this problem so I would happy to use the nugget package.

Thanks

**Comment by vitalyster** [comment]
Just checked out - public setter for JID was added recently and not yet released on NuGet.
Anyway, `BookmarkedConference` still `XElement`, `JID` and `Nick` are just shortcuts to `XElement` properties.
If you want to set nick, you need to add child element like:
```
var nick = new Element(XNamespace.Get(Namespaces.StorageBookmarks) + "nick");
nick.Value = "bla";
bookmarkedConference.Add(nick);
```

**Comment by AtifShahzed** [comment]
Hi,

That's great. Well I am able to JOIN the room and become the participant of the room.
Now I wanted to send the message to the room JID but the problem is message does not deliver to the room . My question is there any special settings are required to send the MUC room message.

Thanks

**Comment by vitalyster** [comment]
See [XEP-0045](https://xmpp.org/extensions/xep-0045.html#message): you should set `type` attribute to `groupchat`

**Comment by AtifShahzed** [comment]
Ok.

Yap there is a Send method but  there is no parameter of type is available to set .
So is this functionality is available or I need to do it through Rest Api or is there any approach to set the custom elements of  xml before sending the message.

Thanks

**Comment by vitalyster** [comment]
Set type on message with XElement methods (SetAttributeValue?) and then Send it

**Comment by AtifShahzed** [comment]
@vitalyster 
Awsome !!!
