### ISSUE TITLE
DnsResolver uses hardcoded DNS server

### ISSUE THREAD

**Issue by LumiProj** [vitalyster/SharpXMPP#71]
Hi,

I am using Xamarin Forms and recently updated with latest Nuget package, it works fine in simulator but on connection it is crashing when I run on physical device.

Thanks

**Comment by vitalyster** [comment]
Please provide a traceback

**Comment by LumiProj** [comment]
Hi,

Following is the exception which I am facing

**List of configured name servers must not be empty.
Parameter name: servers..**

**Comment by vitalyster** [comment]
Do you mean Android emulator or iOS simulator? Which version? Which os version is on device?

**Comment by LumiProj** [comment]
Hi,

Everything is working fine in Android/IOS Simulator, I am facing this crash in physical devices in Android/iois.

**Comment by vitalyster** [comment]
I need the exact OS version for simulators and physical devices you are using

**Comment by LumiProj** [comment]
Hi,

I have tested on iPhone 11 Pro , iPhone 11 Pro MAX, iPhone 6,
I have tested all simulators from iPhone 6 - iPhone 11 Pro max.

**Comment by vitalyster** [comment]
This is NOT operating system version, let me know operating system version on simulator (e.g. iOS 13.7) and on physical device (e.g. iOS 14.0)

**Comment by LumiProj** [comment]
I have tested on 13.7 and 14.0 as well both on simulators and physical devices.

**Comment by vitalyster** [comment]
OK I see DnsClient package does not work on Xamarin correctly for both Android and iOS. Reverted back to own DNS resolver. Issue fixed on master, fixed version should be released on NuGet shortly

**Comment by vitalyster** [comment]
We should revert back to DnsClient, but not use no-args constructor and pass hardcoded DNS server on mobile platforms, see https://github.com/MichaCo/DnsClient.NET/issues/17#issuecomment-864626079
