### ISSUE TITLE
Send friend request

### ISSUE THREAD

**Issue by LumiProj** [vitalyster/SharpXMPP#72]
Hi,

  var roast = client.RosterManager.Roster;

Even at backend I have two friends in roster but this method always return 0
Secondly is there any way I can catch the roaster updates.

Thanks

**Comment by vitalyster** [comment]
Roster updates are received automatically if you send initial presence. Initial roster is requested automatically, make sure initial response is received from server (you should see in XML log query like `<iq type='get' ...><query xmlns='jabber:iq:roster'/></query></iq>` and server should send response like `<iq type='result' ...><query xmlns='jabber:iq:roster'><item name='friend 1' ... /><item name='friend 2' .../></query></iq>`
