### ISSUE TITLE
Error on MUC Join in Xamarin Forms

### ISSUE THREAD

**Issue by LumiProj** [vitalyster/SharpXMPP#79]
var username = "3111";
            var password = "3111";
var Client = new XmppClient
              (new JID($"{username}@blah.com"), password, true);
            Client.ConnectAsync();

            BookmarkedConference bookmarkedConference = new BookmarkedConference();
            bookmarkedConference.SetAttributeValue("JID", "room2@blah.com");
            bookmarkedConference.SetAttributeValue("Nick", "John");

            Client.BookmarkManager.Join
                (bookmarkedConference);

![image](https://user-images.githubusercontent.com/59764810/95023587-545ad780-0697-11eb-8189-cc4e34026fde.png)

**Comment by vitalyster** [comment]
You can not join conference before client is connected, use `SignedIn` event to join when we connected, try something like this:
```
Client.SignedIn += (s, a) => {
 // we are signed in, now it is safe to join conferences
}
```

**Comment by LumiProj** [comment]
Hi,

Thanks a lot for the prompt response, but the issue is not resolved. I tried in Windows Form app it works fine but in Xamarin forms (iOS/Android) in Simluators/Devices I am getting same error.

Thanks

**Comment by vitalyster** [comment]
I can not reproduce the problem, provide your Xamarin project and I will check it

**Comment by LumiProj** [comment]
Hi,

Please take a look into that .
  private void Client_SignedIn(XmppConnection sender, SignedInArgs e)
        {
            BookmarkedConference bookmarkedConference = new BookmarkedConference();
            bookmarkedConference.SetAttributeValue("JID", "room2@conference.sip.lumieclinic.com");
            bookmarkedConference.SetAttributeValue("Nick", "Atif");

            Client.BookmarkManager.Join(bookmarkedConference    );
        }

I downloaded the code and add reference in m y project manually now on join method JID,Nick is getting null that is the issue.
Can you please help me what's wrong with the joining code.

Thanks

**Comment by vitalyster** [comment]
You should not use `Client` variable, it does not reference your connection, use `sender` inside `Client_SignedIn` handler, like this:
```
((XmppClient)sender).BookmarkManager.Join(bookmarkedConference );
```
